### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by mictadlo** [TBroTeam/Docker#15]
Hi,
Could you please combine all of your docker files inside a `docker-compose.yml` file?

Thank you in advance,

Michal

**Comment by iimog** [comment]
Hi Michal,

thanks for raising this issue. We already have it recorded in #10 
Maybe I can create a compose file later today.

Best,
Markus

**Comment by iimog** [comment]
Hi @mictadlo,
sorry for the delayed response. I finally found some time to work on this issue. Unfortunately it turned out to be harder than I expected. See my comment in #10 and please follow this issue for further updates or comments. I will close this one to have the discussion in one place. I don't think that the current `docker-compose` solution as explained in #10 is any better than the single steps documented in https://tbro-tutorial.readthedocs.io/en/latest/installation.html#docker
Please let me know if a working `docker-compose` setup is essential for you. In that case I will try to find some more time to implement it properly otherwise I'll stick with the separate `docker` commands for now.
Best,
Markus
